[package]
name = "rustic_factors"
version = "0.1.0"
edition = "2021"

[dependencies]
bnum = { version = "0.11.0", features = ["numtraits", "rand"] }
num-integer = "0.1.46"
num-traits = "0.2.18"
rand = "0.8.5"
